/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TaskEscrow {
  export type BidStruct = {
    id: BigNumberish;
    taskId: BigNumberish;
    agent: AddressLike;
    amount: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    message: string;
  };

  export type BidStructOutput = [
    id: bigint,
    taskId: bigint,
    agent: string,
    amount: bigint,
    status: bigint,
    createdAt: bigint,
    message: string
  ] & {
    id: bigint;
    taskId: bigint;
    agent: string;
    amount: bigint;
    status: bigint;
    createdAt: bigint;
    message: string;
  };

  export type TaskStruct = {
    id: BigNumberish;
    creator: AddressLike;
    assignedAgent: AddressLike;
    reward: BigNumberish;
    deadline: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    completedAt: BigNumberish;
    title: string;
    description: string;
  };

  export type TaskStructOutput = [
    id: bigint,
    creator: string,
    assignedAgent: string,
    reward: bigint,
    deadline: bigint,
    status: bigint,
    createdAt: bigint,
    completedAt: bigint,
    title: string,
    description: string
  ] & {
    id: bigint;
    creator: string;
    assignedAgent: string;
    reward: bigint;
    deadline: bigint;
    status: bigint;
    createdAt: bigint;
    completedAt: bigint;
    title: string;
    description: string;
  };
}

export interface TaskEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptBid"
      | "agentTasks"
      | "approveAndRelease"
      | "bidCounter"
      | "bids"
      | "cancelTask"
      | "completeTask"
      | "createTask"
      | "creatorTasks"
      | "depositEscrow"
      | "deposits"
      | "getAgentTasks"
      | "getBid"
      | "getCreatorTasks"
      | "getTask"
      | "getTaskBids"
      | "owner"
      | "paymentToken"
      | "raiseDispute"
      | "rejectBid"
      | "renounceOwnership"
      | "resolveDispute"
      | "submitBid"
      | "taskBids"
      | "taskCounter"
      | "tasks"
      | "transferOwnership"
      | "withdrawBid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BidStatusChanged"
      | "BidSubmitted"
      | "DepositMade"
      | "DisputeRaised"
      | "DisputeResolved"
      | "OwnershipTransferred"
      | "PaymentReleased"
      | "TaskCancelled"
      | "TaskCreated"
      | "TaskResultSubmitted"
      | "TaskUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentTasks",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveAndRelease",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bidCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bids", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTask",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creatorTasks",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositEscrow",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentTasks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorTasks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTaskBids",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectBid",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitBid",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "taskBids",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "taskCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBid",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "acceptBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agentTasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveAndRelease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bidCounter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bids", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creatorTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositEscrow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorTasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTaskBids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rejectBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitBid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "taskBids", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "taskCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBid",
    data: BytesLike
  ): Result;
}

export namespace BidStatusChangedEvent {
  export type InputTuple = [
    bidId: BigNumberish,
    taskId: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [bidId: bigint, taskId: bigint, newStatus: bigint];
  export interface OutputObject {
    bidId: bigint;
    taskId: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BidSubmittedEvent {
  export type InputTuple = [
    bidId: BigNumberish,
    taskId: BigNumberish,
    agent: AddressLike,
    amount: BigNumberish,
    message: string
  ];
  export type OutputTuple = [
    bidId: bigint,
    taskId: bigint,
    agent: string,
    amount: bigint,
    message: string
  ];
  export interface OutputObject {
    bidId: bigint;
    taskId: bigint;
    agent: string;
    amount: bigint;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositMadeEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    depositor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, depositor: string, amount: bigint];
  export interface OutputObject {
    taskId: bigint;
    depositor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [taskId: BigNumberish, raisedBy: AddressLike];
  export type OutputTuple = [taskId: bigint, raisedBy: string];
  export interface OutputObject {
    taskId: bigint;
    raisedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    winner: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, winner: string, amount: bigint];
  export interface OutputObject {
    taskId: bigint;
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    agent: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, agent: string, amount: bigint];
  export interface OutputObject {
    taskId: bigint;
    agent: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    creator: AddressLike,
    refundAmount: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    creator: string,
    refundAmount: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    creator: string;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    creator: AddressLike,
    reward: BigNumberish,
    title: string,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    creator: string,
    reward: bigint,
    title: string,
    deadline: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    creator: string;
    reward: bigint;
    title: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskResultSubmittedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    agent: AddressLike,
    resultHash: string
  ];
  export type OutputTuple = [taskId: bigint, agent: string, resultHash: string];
  export interface OutputObject {
    taskId: bigint;
    agent: string;
    resultHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskUpdatedEvent {
  export type InputTuple = [taskId: BigNumberish, newStatus: BigNumberish];
  export type OutputTuple = [taskId: bigint, newStatus: bigint];
  export interface OutputObject {
    taskId: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TaskEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): TaskEscrow;
  waitForDeployment(): Promise<this>;

  interface: TaskEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptBid: TypedContractMethod<[_bidId: BigNumberish], [void], "nonpayable">;

  agentTasks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  approveAndRelease: TypedContractMethod<
    [_taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  bidCounter: TypedContractMethod<[], [bigint], "view">;

  bids: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint, bigint, string] & {
        id: bigint;
        taskId: bigint;
        agent: string;
        amount: bigint;
        status: bigint;
        createdAt: bigint;
        message: string;
      }
    ],
    "view"
  >;

  cancelTask: TypedContractMethod<
    [_taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeTask: TypedContractMethod<
    [_taskId: BigNumberish, _resultHash: string],
    [void],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _reward: BigNumberish,
      _deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  creatorTasks: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  depositEscrow: TypedContractMethod<
    [_taskId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposits: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getAgentTasks: TypedContractMethod<[_agent: AddressLike], [bigint[]], "view">;

  getBid: TypedContractMethod<
    [_bidId: BigNumberish],
    [TaskEscrow.BidStructOutput],
    "view"
  >;

  getCreatorTasks: TypedContractMethod<
    [_creator: AddressLike],
    [bigint[]],
    "view"
  >;

  getTask: TypedContractMethod<
    [_taskId: BigNumberish],
    [TaskEscrow.TaskStructOutput],
    "view"
  >;

  getTaskBids: TypedContractMethod<
    [_taskId: BigNumberish],
    [TaskEscrow.BidStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  raiseDispute: TypedContractMethod<
    [_taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  rejectBid: TypedContractMethod<[_bidId: BigNumberish], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resolveDispute: TypedContractMethod<
    [
      _taskId: BigNumberish,
      _winner: AddressLike,
      _creatorPercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitBid: TypedContractMethod<
    [_taskId: BigNumberish, _amount: BigNumberish, _message: string],
    [bigint],
    "nonpayable"
  >;

  taskBids: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  taskCounter: TypedContractMethod<[], [bigint], "view">;

  tasks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        id: bigint;
        creator: string;
        assignedAgent: string;
        reward: bigint;
        deadline: bigint;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        title: string;
        description: string;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawBid: TypedContractMethod<
    [_bidId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptBid"
  ): TypedContractMethod<[_bidId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "agentTasks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approveAndRelease"
  ): TypedContractMethod<[_taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bidCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bids"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, bigint, bigint, string] & {
        id: bigint;
        taskId: bigint;
        agent: string;
        amount: bigint;
        status: bigint;
        createdAt: bigint;
        message: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[_taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeTask"
  ): TypedContractMethod<
    [_taskId: BigNumberish, _resultHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _reward: BigNumberish,
      _deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creatorTasks"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositEscrow"
  ): TypedContractMethod<
    [_taskId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposits"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgentTasks"
  ): TypedContractMethod<[_agent: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getBid"
  ): TypedContractMethod<
    [_bidId: BigNumberish],
    [TaskEscrow.BidStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreatorTasks"
  ): TypedContractMethod<[_creator: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [_taskId: BigNumberish],
    [TaskEscrow.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTaskBids"
  ): TypedContractMethod<
    [_taskId: BigNumberish],
    [TaskEscrow.BidStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[_taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rejectBid"
  ): TypedContractMethod<[_bidId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [
      _taskId: BigNumberish,
      _winner: AddressLike,
      _creatorPercent: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitBid"
  ): TypedContractMethod<
    [_taskId: BigNumberish, _amount: BigNumberish, _message: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "taskBids"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "taskCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string
      ] & {
        id: bigint;
        creator: string;
        assignedAgent: string;
        reward: bigint;
        deadline: bigint;
        status: bigint;
        createdAt: bigint;
        completedAt: bigint;
        title: string;
        description: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawBid"
  ): TypedContractMethod<[_bidId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BidStatusChanged"
  ): TypedContractEvent<
    BidStatusChangedEvent.InputTuple,
    BidStatusChangedEvent.OutputTuple,
    BidStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "BidSubmitted"
  ): TypedContractEvent<
    BidSubmittedEvent.InputTuple,
    BidSubmittedEvent.OutputTuple,
    BidSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "DepositMade"
  ): TypedContractEvent<
    DepositMadeEvent.InputTuple,
    DepositMadeEvent.OutputTuple,
    DepositMadeEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskResultSubmitted"
  ): TypedContractEvent<
    TaskResultSubmittedEvent.InputTuple,
    TaskResultSubmittedEvent.OutputTuple,
    TaskResultSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "TaskUpdated"
  ): TypedContractEvent<
    TaskUpdatedEvent.InputTuple,
    TaskUpdatedEvent.OutputTuple,
    TaskUpdatedEvent.OutputObject
  >;

  filters: {
    "BidStatusChanged(uint256,uint256,uint8)": TypedContractEvent<
      BidStatusChangedEvent.InputTuple,
      BidStatusChangedEvent.OutputTuple,
      BidStatusChangedEvent.OutputObject
    >;
    BidStatusChanged: TypedContractEvent<
      BidStatusChangedEvent.InputTuple,
      BidStatusChangedEvent.OutputTuple,
      BidStatusChangedEvent.OutputObject
    >;

    "BidSubmitted(uint256,uint256,address,uint256,string)": TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;
    BidSubmitted: TypedContractEvent<
      BidSubmittedEvent.InputTuple,
      BidSubmittedEvent.OutputTuple,
      BidSubmittedEvent.OutputObject
    >;

    "DepositMade(uint256,address,uint256)": TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;
    DepositMade: TypedContractEvent<
      DepositMadeEvent.InputTuple,
      DepositMadeEvent.OutputTuple,
      DepositMadeEvent.OutputObject
    >;

    "DisputeRaised(uint256,address)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(uint256,address,uint256)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentReleased(uint256,address,uint256)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;

    "TaskCancelled(uint256,address,uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskCreated(uint256,address,uint256,string,uint40)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;

    "TaskResultSubmitted(uint256,address,string)": TypedContractEvent<
      TaskResultSubmittedEvent.InputTuple,
      TaskResultSubmittedEvent.OutputTuple,
      TaskResultSubmittedEvent.OutputObject
    >;
    TaskResultSubmitted: TypedContractEvent<
      TaskResultSubmittedEvent.InputTuple,
      TaskResultSubmittedEvent.OutputTuple,
      TaskResultSubmittedEvent.OutputObject
    >;

    "TaskUpdated(uint256,uint8)": TypedContractEvent<
      TaskUpdatedEvent.InputTuple,
      TaskUpdatedEvent.OutputTuple,
      TaskUpdatedEvent.OutputObject
    >;
    TaskUpdated: TypedContractEvent<
      TaskUpdatedEvent.InputTuple,
      TaskUpdatedEvent.OutputTuple,
      TaskUpdatedEvent.OutputObject
    >;
  };
}
